Controllers/API/ClimateSurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Milieusysteem.Data;
using Milieusysteem.Models;

namespace Milieusysteem.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ClimateSurveysController : ControllerBase
    {
        private readonly MilieuSysteemDb _context;

        public ClimateSurveysController(MilieuSysteemDb context)
        {
            _context = context;
        }

        // GET: api/ClimateSurveys
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ClimateSurvey>>> GetclimateSurveys()
        {
          if (_context.climateSurveys == null)
          {
              return NotFound();
          }
            return await _context.climateSurveys.ToListAsync();
        }

        // GET: api/ClimateSurveys/5
        [HttpGet("{id}")]
        public async Task<ActionResult<ClimateSurvey>> GetClimateSurvey(int id)
        {
          if (_context.climateSurveys == null)
          {
              return NotFound();
          }
            var climateSurvey = await _context.climateSurveys.FindAsync(id);

            if (climateSurvey == null)
            {
                return NotFound();
            }

            return climateSurvey;
        }

        // PUT: api/ClimateSurveys/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutClimateSurvey(int id, ClimateSurvey climateSurvey)
        {
            if (id != climateSurvey.Id)
            {
                return BadRequest();
            }

            _context.Entry(climateSurvey).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClimateSurveyExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/ClimateSurveys
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<ClimateSurvey>> PostClimateSurvey(ClimateSurvey climateSurvey)
        {
          if (_context.climateSurveys == null)
          {
              return Problem("Entity set 'MilieuSysteemDb.climateSurveys'  is null.");
          }
            _context.climateSurveys.Add(climateSurvey);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetClimateSurvey", new { id = climateSurvey.Id }, climateSurvey);
        }

        // DELETE: api/ClimateSurveys/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteClimateSurvey(int id)
        {
            if (_context.climateSurveys == null)
            {
                return NotFound();
            }
            var climateSurvey = await _context.climateSurveys.FindAsync(id);
            if (climateSurvey == null)
            {
                return NotFound();
            }

            _context.climateSurveys.Remove(climateSurvey);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool ClimateSurveyExists(int id)
        {
            return (_context.climateSurveys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Milieusysteem.Data;
using Milieusysteem.Models;
using NuGet.DependencyResolver;

namespace Milieusysteem.Controllers
{
    public class ClassesController : Controller
    {
        private readonly MilieuSysteemDb _context;
        private readonly IHttpContextAccessor _contextAccessor;

        public ClassesController(MilieuSysteemDb context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _contextAccessor = httpContextAccessor;
        }

        // GET: Classes
        public async Task<IActionResult> Index()
        {
              return _context.Class != null ? 
                          View(await _context.Class.ToListAsync()) :
                          Problem("Entity set 'MilieuSysteemDb.Class'  is null.");
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class.FindAsync(id);
            if (@class == null)
            {
                return NotFound();
            }
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        

        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Class @class)
        {
            if (id != @class.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    @class.TeacherId = int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId"));
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //Teacher teacher = _context.Teachers.FirstOrDefault(t => t.Id == int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId")));
                Teacher teacher = _context.Teachers.FirstOrDefault(t => t.Id == int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId")));
                List<Class> classes = new List<Class>();
                foreach (var Class in _context.Classes.ToList())
                {
                    if (Class.TeacherId == teacher.Id)
                    {
                        classes.Add(Class);
                    }
                }
                teacher.Classes = classes;
                return RedirectToAction("Log_In", "Home", teacher);
                //return View("TeacherHome", teacher);
                //return RedirectToAction("Log_In", "Home", teacher);
                //return View("Views/Home/TeacherHome", teacher);
            }

            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Class == null)
            {
                return NotFound();
            }

            var @class = await _context.Class
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Class == null)
            {
                return Problem("Entity set 'MilieuSysteemDb.Class'  is null.");
            }
            var @class = await _context.Class.FindAsync(id);
            if (@class != null)
            {
                _context.Class.Remove(@class);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));\
            Teacher teacher = _context.Teachers.FirstOrDefault(t => t.Id == int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId")));
            List<Class> classes = new List<Class>();
            foreach (var Class in _context.Classes.ToList())
            {
                if (Class.TeacherId == teacher.Id)
                {
                    classes.Add(Class);
                }
            }
            teacher.Classes = classes;
            return RedirectToAction("Log_In", "Home", teacher);
        }

        private bool ClassExists(int id)
        {
          return (_context.Class?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> ViewSurveyOutcomes(int? id)
        {
            if(id != null)
            {
                Class @class = _context.Classes.FirstOrDefault(x => x.Id == id);
                List<SurveyCounter> surveyCounters = _context.surveyCounters.ToList();
                
                
                foreach(SurveyCounter surveyCounter in surveyCounters)
                {
                    List<ClimateSurvey> climateSurveys = _context.climateSurveys.ToList();
                    List<Choice> choices = _context.choices.ToList();
                    List<ChoiceAmount> choiceAmounts = _context.ChoiceAmounts.ToList();
                    ClimateSurvey climateSurvey = new ClimateSurvey();
                    List<ClimateSurvey> finishedSurveys = new List<ClimateSurvey>();
                    List<Choice> surveyChoices = new List<Choice>();
                    if (surveyCounter.ClassId == id)
                    {
                        foreach (ClimateSurvey survey in climateSurveys)
                        {
                            if(survey.Id == surveyCounter.ClimateSurveyId)
                            {
                                climateSurvey = survey;
                                climateSurvey.SurveyCountId = surveyCounter.Id;
                                climateSurvey.ClassId = id;

                                foreach (Choice choice in choices)
                                {
                                    if (choice.ClimateSurveyId == climateSurvey.Id)
                                    {
                                        foreach (ChoiceAmount amount in choiceAmounts)
                                        {
                                            if (amount.ChoiceId == choice.Id & amount.SurveyCounterId == climateSurvey.SurveyCountId)
                                            {
                                                choice.AmountOfVotes = amount.ChoiceCount;
                                                climateSurvey.SurveyChoices.Add(choice);
                                                
                                            }
                                        }
                                    }
                                }

                                @class.FinishedSurveys.Add(climateSurvey);
                                
                            }
                        }
                    }
                    
                }
                

                return View(@class); 
            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Milieusysteem.Data;
using Milieusysteem.Models;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using NuGet.DependencyResolver;

namespace Milieusysteem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MilieuSysteemDb _context;
        private readonly IHttpContextAccessor _sessionStorage;
        

        public HomeController(ILogger<HomeController> logger, MilieuSysteemDb context, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _context = context;
            _sessionStorage = httpContextAccessor;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult CreateAccount()
        {
            return View();
        }

        public async Task<IActionResult> Create([Bind("Id,Email,Password")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                List<Teacher> teachers = _context.Teachers.ToList();
                if (teachers.Any(contextTeacher => contextTeacher.Email == teacher.Email))
                {
                    return View("CreateAccount");
                }
            }
            _context.Add(teacher);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            
            
            return View("Index");
            
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Log_in([Bind("Id,Email,Password")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                List<Teacher> teachers = _context.Teachers.ToList();
                if (teachers.Any(contextTeacher => contextTeacher.Email == teacher.Email & contextTeacher.Password == teacher.Password))
                {
                    Teacher _teacher = _context.Teachers.FirstOrDefault(x => x.Email == teacher.Email);
                    _sessionStorage.HttpContext.Session.SetString("LoggedInTeacherId", _teacher.Id.ToString());
                    List<Class> classes = new List<Class>();
                    foreach(var Class in _context.Classes.ToList())
                    {
                        if(Class.TeacherId == _teacher.Id)
                        {
                            classes.Add(Class);
                        }
                    }
                    _teacher.Classes = classes;
                    return View("TeacherHome", _teacher);
                }
            }
            return View("index");
        }
        public IActionResult CreateClass()
        {
            return View();
        }

        public async Task<IActionResult> CreateClassButton([Bind("Id,Name")] Class @class)
        {
            if (ModelState.IsValid)
            {
                @class.TeacherId = int.Parse(_sessionStorage.HttpContext.Session.GetString("LoggedInTeacherId"));
                _context.Add(@class);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                Teacher teacher = _context.Teachers.FirstOrDefault(t => t.Id == int.Parse(_sessionStorage.HttpContext.Session.GetString("LoggedInTeacherId")));
                teacher.Classes = _context.Classes.ToList();
                return View("TeacherHome", teacher);
            }
            Teacher _teacher = _context.Teachers.FirstOrDefault(t => t.Id == int.Parse(_sessionStorage.HttpContext.Session.GetString("LoggedInTeacherId")));
            _teacher.Classes = _context.Classes.ToList();
            return View("TeacherHome", _teacher);
            //return View(@class);
        }
        public IActionResult ClassPage()
        {
            return View();
        }

        public IActionResult CreateSurvey()
        {
            return RedirectToAction("Create", "ClimateSurveys");
        }

        public async Task<IActionResult> DoSurvey(int? id)
        {
            if (id != null)
            {

                Class _class = _context.Classes.FirstOrDefault(t => t.Id == id);
                _sessionStorage.HttpContext.Session.SetString("ClassId", id.ToString());
                return RedirectToAction("SelectSurvey", "ClimateSurveys", _class);
            }
            else { return View(); }
        }
    }
}

Views/Home/ClassPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/CreateClass.cshtml
@model Milieusysteem.Models.Class;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Creeer klas</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateClassButton">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/Index.cshtml
@model Milieusysteem.Models.Teacher;
@{
    ViewData["Title"] = "Home Page";
}

<h1>Log in</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Log_in">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log in" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="text-center">
    <p>
        <a asp-action="CreateAccount">Maak leraar account</a>
    </p>
</div>

Views/Home/TeacherHome.cshtml
@model Milieusysteem.Models.Teacher
@inject IHttpContextAccessor Storage;

<h1>
    Welkom @Model.Email @Storage.HttpContext.Session.GetString("LoggedInTeacherId")
</h1>


    <div>
    <a asp-action="CreateClass"><button class="btn btn-primary">Creeer klas</button></a>
    </div>

<p></p>

    <div>
        <a asp-action="CreateSurvey"><button class="btn btn-primary">Creeer enquete</button></a>
    @*<input type="button" < asp-controller="HomeController"  asp-action="CreateSurvey"  value="Maak enquete" class="btn btn-primary" />*@
    </div>
    <p></p>
<div>
    <a asp-action="ViewSurveys" asp-controller="ClimateSurveys"><button class="btn btn-primary">Bekijk enquetes</button></a>
    @*<input type="button" < asp-controller="HomeController"  asp-action="CreateSurvey"  value="Maak enquete" class="btn btn-primary" />*@
</div>
<p></p>
<main role="main">


    <div class="container">
        <div class="row">
            @foreach (var item in Model.Classes.ToList())
            {

                <div class="col-md-4">
                    <h2>@item.Name</h2>
                    <p></p>
                    <a asp-action="ClassPage"><button class="btn btn-primary">Ga naar klaspagina</button></a>
                    <p></p>
                    <p>
                        <a asp-action ="DoSurvey" asp-route-id="@item.Id"><button class="btn btn-primary">Doe enquete</button></a>
                    </p>
                    <p></p>
                    <p>
                        <a asp-action="ViewSurveyOutcomes" asp-controller="Classes" asp-route-id="@item.Id"><button class="btn btn-primary">Bekijk enquete-uitkomsten</button></a>
                    </p>
                    <p></p>
                    <p>
                        <a asp-action="Edit" asp-controller="Classes" asp-route-id="@item.Id"><button class="btn btn-primary">Pas klas aan</button></a>
                    </p>
                    <p>
                        <a asp-action="Delete" asp-controller="Classes" asp-route-id="@item.Id"><button class="btn btn-primary">Verwijder klas</button></a>
                    </p>
                </div>
                
            }
        </div> 

</main>

Views/Home/TeacherLogIn.cshtml
@model Milieusysteem.Models.Teacher

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>
   Welkom @Model.Email
</h1>