Models/ClimateSurvey.cs
namespace Milieusysteem.Models
{
    public class ClimateSurvey
    {
        public int Id { get; set; }
        public string SurveyQuestion { get; set; }
        public int TeacherId { get; set; }
        public ICollection<Choice>? SurveyChoices { get; set; } = new List<Choice>();
        public int? ClassId { get; set; }
        public int? SurveyCountId { get; set; }

    }
}

Controllers/API/ClimateSurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Milieusysteem.Data;
using Milieusysteem.Models;

namespace Milieusysteem.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ClimateSurveysController : ControllerBase
    {
        private readonly MilieuSysteemDb _context;

        public ClimateSurveysController(MilieuSysteemDb context)
        {
            _context = context;
        }

        // GET: api/ClimateSurveys
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ClimateSurvey>>> GetclimateSurveys()
        {
          if (_context.climateSurveys == null)
          {
              return NotFound();
          }
            return await _context.climateSurveys.ToListAsync();
        }

        // GET: api/ClimateSurveys/5
        [HttpGet("{id}")]
        public async Task<ActionResult<ClimateSurvey>> GetClimateSurvey(int id)
        {
          if (_context.climateSurveys == null)
          {
              return NotFound();
          }
            var climateSurvey = await _context.climateSurveys.FindAsync(id);

            if (climateSurvey == null)
            {
                return NotFound();
            }

            return climateSurvey;
        }

        // PUT: api/ClimateSurveys/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutClimateSurvey(int id, ClimateSurvey climateSurvey)
        {
            if (id != climateSurvey.Id)
            {
                return BadRequest();
            }

            _context.Entry(climateSurvey).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClimateSurveyExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/ClimateSurveys
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<ClimateSurvey>> PostClimateSurvey(ClimateSurvey climateSurvey)
        {
          if (_context.climateSurveys == null)
          {
              return Problem("Entity set 'MilieuSysteemDb.climateSurveys'  is null.");
          }
            _context.climateSurveys.Add(climateSurvey);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetClimateSurvey", new { id = climateSurvey.Id }, climateSurvey);
        }

        // DELETE: api/ClimateSurveys/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteClimateSurvey(int id)
        {
            if (_context.climateSurveys == null)
            {
                return NotFound();
            }
            var climateSurvey = await _context.climateSurveys.FindAsync(id);
            if (climateSurvey == null)
            {
                return NotFound();
            }

            _context.climateSurveys.Remove(climateSurvey);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool ClimateSurveyExists(int id)
        {
            return (_context.climateSurveys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ClimateSurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.EntityFrameworkCore;
using Milieusysteem.Data;
using Milieusysteem.Models;
using Newtonsoft.Json;

namespace Milieusysteem.Controllers
{
    public class ClimateSurveysController : Controller
    {
        private readonly MilieuSysteemDb _context;
        private readonly IHttpContextAccessor _contextAccessor;

        public ClimateSurveysController(MilieuSysteemDb context, IHttpContextAccessor contextAccessor)
        {
            _context = context;
            _contextAccessor = contextAccessor;
        }

        // GET: ClimateSurveys
        public async Task<IActionResult> Index()
        {
              return _context.climateSurveys != null ? 
                          View(await _context.climateSurveys.ToListAsync()) :
                          Problem("Entity set 'MilieuSysteemDb.climateSurveys'  is null.");
        }

        // GET: ClimateSurveys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.climateSurveys == null)
            {
                return NotFound();
            }

            var climateSurvey = await _context.climateSurveys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (climateSurvey == null)
            {
                return NotFound();
            }

            return View(climateSurvey);
        }

        // GET: ClimateSurveys/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClimateSurveys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SurveyQuestion,TeacherId,ClassId,SurveyCountId")] ClimateSurvey climateSurvey)
        {
            if (ModelState.IsValid)
            {
                List<ClimateSurvey> climateSurveys = _context.climateSurveys.ToList();
                if (climateSurveys.Any(x => x.SurveyQuestion == climateSurvey.SurveyQuestion) == false)
                {
                    climateSurvey.TeacherId = int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId"));

                    _context.Add(climateSurvey);
                    await _context.SaveChangesAsync();
                    List<ClimateSurvey> climatesurveys = _context.climateSurveys.ToList();
                    ClimateSurvey _survey = _context.climateSurveys.FirstOrDefault(survey => survey.SurveyQuestion == climateSurvey.SurveyQuestion);
                    _contextAccessor.HttpContext.Session.SetString("SurveyId", _survey.Id.ToString());

                    return RedirectToAction("Create", "Choices");
                }
                else
                {
                    return View("Create");
                }
            }
            return View(climateSurvey);
        }

        // GET: ClimateSurveys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.climateSurveys == null)
            {
                return NotFound();
            }

            var climateSurvey = await _context.climateSurveys.FindAsync(id);
            if (climateSurvey == null)
            {
                return NotFound();
            }
            return View(climateSurvey);
        }

        // POST: ClimateSurveys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SurveyQuestion,TeacherId,ClassId,SurveyCountId")] ClimateSurvey climateSurvey)
        {
            if (id != climateSurvey.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(climateSurvey);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClimateSurveyExists(climateSurvey.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(climateSurvey);
        }

        // GET: ClimateSurveys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.climateSurveys == null)
            {
                return NotFound();
            }

            var climateSurvey = await _context.climateSurveys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (climateSurvey == null)
            {
                return NotFound();
            }

            return View(climateSurvey);
        }

        // POST: ClimateSurveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.climateSurveys == null)
            {
                return Problem("Entity set 'MilieuSysteemDb.climateSurveys'  is null.");
            }
            var climateSurvey = await _context.climateSurveys.FindAsync(id);
            if (climateSurvey != null)
            {
                _context.climateSurveys.Remove(climateSurvey);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClimateSurveyExists(int id)
        {
          return (_context.climateSurveys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> ViewSurveys()
        {
            Teacher teacher = _context.Teachers.FirstOrDefault(x => x.Id == int.Parse(_contextAccessor.HttpContext.Session.GetString("LoggedInTeacherId")));
            List<ClimateSurvey> climateSurveys = new List<ClimateSurvey>();
            foreach(ClimateSurvey _climateSurvey in _context.climateSurveys.ToList())
            {
                if(_climateSurvey.TeacherId == teacher.Id)
                {
                    climateSurveys.Add(_climateSurvey);
                }
            }
            teacher.ClimateSurveys = climateSurveys;
            return View(teacher);
        }
        
        public async Task<IActionResult> ViewQuestions()
        {
            return View();
        }

        public async Task<IActionResult> SelectSurvey(int? id)
        {
            if(id != null)
            {
                _contextAccessor.HttpContext.Session.SetString("ClassId", id.ToString());
                return View(_context.climateSurveys.ToList());
            }

            return View();
        }
        public async Task<IActionResult> DoSurvey(int? id)
        {
            if(id != null)
            {
                _contextAccessor.HttpContext.Session.SetInt32("VoteAmount", 0);
                ClimateSurvey climateSurvey = _context.climateSurveys.FirstOrDefault(x => x.Id == id);
                List<Choice> choices = new List<Choice>();
                foreach(Choice choice in _context.choices.ToList())
                {
                    if (choice.ClimateSurveyId == id)
                    {
                        choices.Add(choice);  
                    }
                }
                _contextAccessor.HttpContext.Session.SetString("ChoiceCounter", JsonConvert.SerializeObject(choices));
                SurveyCounter surveyCounter = new SurveyCounter();
                surveyCounter.ClimateSurveyId = climateSurvey.Id;
                surveyCounter.ClassId = int.Parse(_contextAccessor.HttpContext.Session.GetString("ClassId"));
                _context.surveyCounters.Add(surveyCounter);
                await _context.SaveChangesAsync();
                climateSurvey.SurveyCountId = _context.surveyCounters.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                foreach(Choice choice in choices)
                {
                    ChoiceAmount choiceAmount = new ChoiceAmount();
                    choiceAmount.SurveyCounterId = (int)climateSurvey.SurveyCountId;
                    choiceAmount.ChoiceId = choice.Id;
                    _context.ChoiceAmounts.Add(choiceAmount);
                    await _context.SaveChangesAsync();
                }
                climateSurvey.SurveyChoices = choices;
                return View(climateSurvey);
            }
            return View();
        }

        public async Task<IActionResult> Vote(int? id)
        {
            if(id != null)
            {
                int voteAmount = (int)_contextAccessor.HttpContext.Session.GetInt32("VoteAmount") + 1;
                _contextAccessor.HttpContext.Session.SetInt32("VoteAmount", voteAmount);
                int climateSurveyCountId = _context.surveyCounters.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                foreach(ChoiceAmount choiceAmount in _context.ChoiceAmounts)
                {
                    if (choiceAmount.SurveyCounterId == climateSurveyCountId && choiceAmount.ChoiceId == id)
                    {
                        choiceAmount.ChoiceCount += 1;
                        _context.ChoiceAmounts.Update(choiceAmount);
                        
                    }
                }

Views/ClimateSurveys/Create.cshtml
@model Milieusysteem.Models.ClimateSurvey

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ClimateSurvey</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SurveyQuestion" class="control-label"></label>
                <input asp-for="SurveyQuestion" class="form-control" />
                <span asp-validation-for="SurveyQuestion" class="text-danger"></span>
            </div>
          @*  <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <input asp-for="TeacherId" class="form-control" />
                <span asp-validation-for="TeacherId" class="text-danger"></span>
            </div>@*@
            @*<div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="SurveyCountId" class="control-label"></label>
                <input asp-for="SurveyCountId" class="form-control" />
                <span asp-validation-for="SurveyCountId" class="text-danger"></span>
            </div>*@
            <p></p>
            <div class="form-group">
                <input type="submit" value="Create questions" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ClimateSurveys/Delete.cshtml
@model Milieusysteem.Models.ClimateSurvey

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClimateSurvey</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurveyQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurveyQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeacherId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurveyCountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurveyCountId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ClimateSurveys/Details.cshtml
@model Milieusysteem.Models.ClimateSurvey

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClimateSurvey</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurveyQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurveyQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeacherId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurveyCountId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurveyCountId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/ClimateSurveys/DoSurvey.cshtml
@model Milieusysteem.Models.ClimateSurvey;
@inject IHttpContextAccessor Session;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h4>
    Stemmen uitgebracht: @Session.HttpContext.Session.GetInt32("VoteAmount")
</h4>
<div class="container">
<div class="row">
@foreach(Choice choice in Model.SurveyChoices)
{
    <div class="col md-4">
    <a asp-action="Vote" asp-route-id=@choice.Id><button class="btn btn-primary">@choice.ChoiceTekst</button></a>
            </div>
}
    </div>
</div>
<a asp-action="ViewVoteResults"> <button class="btn btn-primary">Bekijk resultaten</button></a>

Views/ClimateSurveys/Edit.cshtml
@model Milieusysteem.Models.ClimateSurvey

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ClimateSurvey</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SurveyQuestion" class="control-label"></label>
                <input asp-for="SurveyQuestion" class="form-control" />
                <span asp-validation-for="SurveyQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeacherId" class="control-label"></label>
                <input asp-for="TeacherId" class="form-control" />
                <span asp-validation-for="TeacherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurveyCountId" class="control-label"></label>
                <input asp-for="SurveyCountId" class="form-control" />
                <span asp-validation-for="SurveyCountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ClimateSurveys/Index.cshtml
@model IEnumerable<Milieusysteem.Models.ClimateSurvey>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SurveyQuestion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClassId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SurveyCountId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SurveyQuestion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeacherId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SurveyCountId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/ClimateSurveys/SelectSurvey.cshtml
@model IEnumerable<Milieusysteem.Models.ClimateSurvey>;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@if(Model != null)
{
    <div class="container">
    <div class="row">
    @foreach(ClimateSurvey climateSurvey in Model)
    {
        <div class="col-md-4">
        <h1>
            @climateSurvey.SurveyQuestion;
        </h1>
        <a asp-action="DoSurvey" asp-route-id="@climateSurvey.Id"><button class="btn btn-primary">Selecteer enquete</button></a>
                </div>
    }
        </div>
    </div>
}

Views/ClimateSurveys/ViewSurveys.cshtml
@model Milieusysteem.Models.Teacher;
@*
    For more information on enabling MVC for empty projClects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@foreach (var item in Model.ClimateSurveys.ToList())
{

    <div class="col-md-4">
        <h2>@item.SurveyQuestion</h2>
        <p></p>
        <a asp-action="ViewQuestions"><button class="btn btn-primary">Bekijk vragen</button></a>
        <p></p>
        <p>
            <a asp-action="Edit" asp-controller="ClimateSurveys" asp-route-id="@item.Id"><button class="btn btn-primary">Pas vragen aan</button></a>
        </p>
        <p>
            <a asp-action="Delete" asp-controller="ClimateSurveys" asp-route-id="@item.Id"><button class="btn btn-primary">Verwijder enquete</button></a>
        </p>
    </div>

}

Views/ClimateSurveys/ViewVoteResults.cshtml
@model Milieusysteem.Models.ClimateSurvey;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>@Model.SurveyChoices.OrderByDescending(x => x.AmountOfVotes).ToList()[0].Advice</h1>
<p></p>
<div class="container">
    <div class="row">
        @foreach(Choice choice in Model.SurveyChoices)
        {
            <div class="col-md-4">
               <p>@choice.ChoiceTekst @choice.AmountOfVotes</p>
            </div>
        }
    </div>
    <p></p>
    <a asp-action="SurveyOutcomesToTeacherHome"><button class="btn btn-primary">Terug naar dashbord</button></a>
</div>